#   Finding a Motif in DNA
'''
Given: Two DNA strings s and t (each of length at most 1 kbp).

Return: All locations of t as a substring of s.
'''
def find_motif(s:str, t:str)->list:
    n = len(s)
    k = len(t)
    index = []
    for i in range(len(s)-k+1):
        if s[i:i+k] == t:
            index.append(i)
    s_index = [i + 1 for i in index]
    return s_index

def main():
    s = 'ACAATCAGAACGTACGCACATTGAGAACGTGAGAACGTAGGGTACGAGAACGTCAGAACGTCCAGAACGTTGAGAACGTGTAGAACGTTTAGAACGTTAAGAACGTTCGCTGCGTAGAACGTTACACAGAACGTTAGAACGTGAGAACGTAGAACGTTAGAACGTGTCTGCGGAAGAACGTAAGAACGTGAGAACGTACAGAACGTAGAACGTGCTAGAACGTAAAGAACGTGCCCGCCTAGAACGTCAAGAGAACGTAGAGAACGTATGTCTCCCTTCAGGGCGGTTATTAGAACGTTAGAACGTAGAACGTGGAAGAACGTCAAGAACGTTGGCTAAGAACGTAAGAACGTCAGAACGTGTAGAACGTAAGAACGTTAGAACGTAGAACGTAGAACGTCGGAAGAACGTGAGAACGTCCCTAAGAACGTGGTCAGAACGTATTCAACTAAGAACGTAATAGAACGTTGTACTATAGCCGTGAGAAGAACGTGAAGAACGTTGGAAGAACGTAGAACGTTAAGAACGTCAGAACGTCAGAACGTAAGAACGTAGAACGTAGAACGTTAGAACGTTCCAAGGTAACACGAGAACGTAGCTCGAAGAACGTAGAACGTAGAACGTAGAACGTCCTAGAACGTGCATGAGAACGTGGATAAAGAACGTGAAGAACGTACAGAACGTGCAGAACGTAGAACGTGAGAACGTGCAGAACGTAGTCGTGGAGAACGTGCTAGAACGTTAGAGAGAACGTTTAGCGGAGAACGTCAGAACGTTATCGAAGAACGTAGAACGTTAAAGAACGTCTACTCGTAGAACGTCAAGAAGAACGTTGAGAACGTCAGAACGTAGAACGT'
    t = 'AGAACGTAG'
    print(*find_motif(s, t), sep=' ')

if __name__ == "__main__":
    main()